---
- name: Install httpd and restart
  hosts: localhost
  gather_facts: false
  tasks:
  - name: httpd task
    yum:
      name: httpd
      state: present
  - name: restart service 
    service:
      name: httpd
      state: restarted
